org: bando
app: api-rest-arqui-tarea2
service: api-rest-arqui-tarea2

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  temperatura:
    handler: handler.temperatura
    events:
      - httpApi:
          path: /temperatura
          method: get
  UF:
    handler: handler.UF
    events:
      - httpApi:
          path: /uf
          method: get
  dolar:
    handler: handler.dolar
    events:
      - httpApi:
          path: /dolar
          method: get
  crucigrama:
    handler: handler.crucigrama
    events:
      - httpApi:
          path: /crucigrama
          method: get
  apitoday:
    handler: handler.apitoday
    events:
      - httpApi:
          path: /apitoday
          method: get

plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux